# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    metallb.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lrocca <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/14 17:54:22 by lrocca            #+#    #+#              #
#    Updated: 2021/04/15 17:10:40 by lrocca           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.17.0.1-172.17.0.10
