# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    influxdb.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lrocca <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/05/03 19:31:17 by lrocca            #+#    #+#              #
#    Updated: 2021/05/05 17:37:59 by lrocca           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  database: telegraf
  url: http://influxdb:8086
  isDefault: true
  editable: false
  user: admin
  secureJsonData:
    password: "42424242"
  jsonData:
    httpMode: GET
