# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    telegraf.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lrocca <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/20 21:10:51 by lrocca            #+#    #+#              #
#    Updated: 2021/04/21 01:02:46 by lrocca           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: telegraf
  ports:
  - name: telegraf
    protocol: UDP
    port: 8125
    targetPort: 8125
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: ft-services/telegraf
        imagePullPolicy: Never
        ports:
          - name: telegraf
            containerPort: 8125
        volumeMounts:
        - name: telegraf-config-volume
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  labels:
    app: telegraf
data:
  telegraf.conf: |
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      container_names = []
      source_tag = false
      container_name_include = []
      container_name_exclude = []
      timeout = "20s"
      perdevice = true
      total = false
      docker_label_include = []
      docker_label_exclude = []
      tag_env = ["JAVA_HOME", "HEAP_SIZE"]
    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      skip_database_creation = false
      database = "telegraf"
      username = "admin"
      password = "password"
