# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps.yaml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lrocca <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/23 20:20:54 by lrocca            #+#    #+#              #
#    Updated: 2021/04/23 20:35:13 by lrocca           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
  - name: ftp-data
    port: 20
    targetPort: 20
  - name: ftp-connection
    port: 21
    targetPort: 21
  - name: pftp-data-0
    port: 20000
    targetPort: 20000
  - name: pftp-data-1
    port: 20001
    targetPort: 20001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ft-services/ftps
        imagePullPolicy: Never
        ports:
        - name: ftp-data
          containerPort: 20
        - name: ftp-connection
          containerPort: 21
        - name: ftp-data-0
          containerPort: 20000
        - name: ftp-data-1
          containerPort: 20001
        volumeMounts:
          - name: ftps-config
            mountPath: /etc/vsftpd/vsftpd.conf
            subPath: vsftpd.conf
      volumes:
        - name: ftps-config
          configMap:
            name: ftps-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftps-config
data:
  vsftpd.conf: |
    # ################
    # General Settings
    # ################
    listen=YES
    listen_port=21
    listen_ipv6=NO
    write_enable=YES
    # ##################
    # Connection Setting
    # ##################
    local_enable=YES
    force_local_data_ssl=YES
    force_local_logins_ssl=YES
    pam_service_name=vsftpd
    ssl_enable=YES
    # ############
    # Mode Setting
    # ############
    port_enable=NO
    # connect_from_port_20=YES
    # ftp_data_port=20
    pasv_enable=YES
    seccomp_sandbox=NO
    pasv_address=ftps
    pasv_min_port=20000
    pasv_max_port=20001
    # ##################
    # Permission Setting
    # ##################
    local_umask=022
    # ################
    # Security Setting
    # ################
    chroot_local_user=YES
    # ############
    # Log Settings
    # ############
    xferlog_enable=YES
    xferlog_std_format=NO
    xferlog_file=/var/log/vsftpd.log
    # ######################
    # Anonymous User Setting
    # ######################
    anonymous_enable=NO
    allow_anon_ssl=NO
    # ###
    # etc
    # ###
    # isolate_network=NO
    require_ssl_reuse=NO
    validate_cert=YES
    allow_writeable_chroot=YES
    log_ftp_protocol=YES
    rsa_cert_file=/etc/ssl/private/tls.crt
    rsa_private_key_file=/etc/ssl/private/tls.key
